### ISSUE TITLE
Error while running ezfio

### ISSUE THREAD

**Issue by visheshvijay** [earlephilhower/ezfio#17] opened 2017-07-18 15:20 UTC
[root@jaguar54 ezfio-master]# ./ezfio.py -d /dev/nvme1n1 -u 100
Install sdparm to allow model/serial extraction. Continuing.
---------------------------------------------------------------------------
WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! 
THIS TEST WILL DESTROY ANY DATA AND FILESYSTEMS ON  /dev/nvme1n1

Please type the word "yes" and hit return to continue, or anything else to abort.
yes
---------------------------------------------------------------------------

***************************************************************************************************
ezFio test parameters:

               Drive: /dev/nvme1n1
               Model: UNKNOWN
              Serial: UNKNOWN
       AvailCapacity: 2980 GiB
      TestedCapacity: 2980 GiB
                 CPU: Intel Xeon CPU E3-1246 v3 @ 3.50GHz
               Cores: 8
           Frequency: 3500

Test Description                                                        BW(MB/s)      IOPS  Lat(us)
----------------------------------------------------------------------- -------- --------- --------

---Sequential Preconditioning---                                                                   
Sequential Preconditioning Pass 1                                           DONE      DONE     DONE 
Sequential Preconditioning Pass 2                                           DONE      DONE     DONE 

---Sustained Multi-Threaded Sequential Read Tests by Block Size---                                 
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=512              00:02:00          
Unexpected error while running FIO job.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./ezfio.py", line 732, in JobWrapper
    val = o['cmdline'](o)
  File "./ezfio.py", line 591, in <lambda>
    o['runtime'])})
  File "./ezfio.py", line 526, in RunTest
    j = json.loads(out)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=512       ERROR     ERROR    ERROR
ERROR DETECTED, ABORTING TEST RUN.
[root@jaguar54 ezfio-master]# nvme list

**Comment by earlephilhower** [comment] 2017-07-18 16:02
Can you run "fio --version" to report your version?  And if you could ZIP or TAR up the whole test directory and attach that would be helpful, too.

At first glance it looks like you've got a FIO old enough to not have "--output-format json+" support, but w/o the above it's not really possible to tell.

Thx
-EFP3

**Comment by earlephilhower** [comment] 2017-07-23 22:37
I was able to reproduce the failure on Ubuntu 16.04's included FIO version.  It was as suspected, namely the older FIO silently accepting an unknown output-format.

The latest commit fixes this and it seems to work great w/that version and the latest 2.99 from Jens Axboe's repo.

Can you try it and close this if it fixes your problem, or if not give some more info?

**Comment by visheshvijay** [comment] 2017-07-25 10:16
Sure I will try Thanks :)

**Comment by earlephilhower** [comment] 2017-09-05 21:10
Closing due to inactivity.  If this appears again, please let me know.  Thanks! -EFP3

**Closed by earlephilhower** 2017-09-05 21:10 UTC
