### ISSUE TITLE
Test done but shows still runing

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#20] opened 2018-01-20 10:45 UTC
Hi Earle,

I've performed the latest run on the SSD with the latest ezfio and v3.3 FIO.

The test was done but one one  of the entries is  still showing as runnig, FYI:

![image](https://user-images.githubusercontent.com/13221472/35182529-dccdc2e6-fde7-11e7-83e7-cfb61861f539.png)

I'm also sharing  the ZIP  so that  you can investigate.

[ezfio-master.zip](https://github.com/earlephilhower/ezfio/files/1648735/ezfio-master.zip)

Regards

**Comment by earlephilhower** [comment] 2018-01-20 16:41
Howdy,

As only one test runs at a time, and the app can't start another test before the last one exits, this is just a GUI hiccup.  You can see the Open Graphs Sheet is ungreyed, and the attached graph looks great, in fact.

I'll eyeball it, but since it's only related to some message being eaten by the  Windows event system (which is how the GUI is updated from inside Powershell) I don't think there's anything to be done or info in the directory, sorry.

**Comment by coolrecep** [comment] 2018-01-20 17:15
Ok. Just wanted to let you know. Thanks.

**Comment by earlephilhower** [comment] 2018-01-25 20:38
Appreciate the help!  I'm closing this for now.  I've gone over the code and there's nothing obvious where it would miss an event, and I can't reproduce it since it seems to be timing related.  Oh, the fun of asynchronous communications ins a system under heavy load.  I'm going to close this for now, but if it can consistently be repro'd we can re-open it.  Thx! -EFP3

**Closed by earlephilhower** 2018-01-25 20:38 UTC
