### ISSUE TITLE
Invalid Argument

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#14] opened 2017-05-12 15:22 UTC
Trying to launch via BAT file, I get this:

![image](https://cloud.githubusercontent.com/assets/13221472/26004855/e2de52b4-373f-11e7-8df6-fa3e22609516.png)

W10 1703 x64

**Comment by earlephilhower** [comment] 2017-06-12 18:22
I just noticed this bug from a few months back.  I think it's the same as issue #8.

The latest checkin, 3774890, should fix it.  I was able to reproduce the failure in a directory that had a space in the path with the old script, and by using the new script everything just worked.  Quoting strings through nested BAT and PS1 scripts is a right pain.

Try the latest drop, and if it fixes can you close this and #8?  

Thx
-EFP3

**Comment by earlephilhower** [comment] 2017-09-05 21:11
Closing due to inactivity.  If this appears again, please let me know.  Thanks! -EFP3

**Closed by earlephilhower** 2017-09-05 21:11 UTC
